config/routes.rb
RailsCms::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => "site#index"

  match 'page/:id' => 'site#page', :as => 'page', :via => :get

  match 'post/:id' => 'site#post', :as => 'post', :via => :get

  match 'search_results' => 'site#search_results', :as => 'search_results'#, :via => :post

  match 'category/:id' => 'site#category', :as => 'category', :via => :get

  match 'blog' => 'site#blog', :as => 'blog', :via => :get

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  attr_accessible :content, :title, :category_id, :image

  belongs_to :category

  # Validations
  validates :title,       :presence => true
  validates :content,     :presence => true
  validates :category_id, :presence => true

  #Paperclip image
  has_attached_file :image, :styles => { :featured => "870x400", :medium => "300x300>", :thumb => "100x100>" }

end

app/models/blog_posts.rb
class BlogPosts < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title

  has_many :blog_posts
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_presence :data

  def url_content
    url(:content)
  end
end

app/models/site_page.rb
class SitePage < ActiveRecord::Base
  attr_accessible :content, :title

  # Validations
  validates :title,   :presence => true
  validates :content, :presence => true
  
end

app/models/site_pages.rb
class SitePages < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/widget.rb
class Widget < ActiveRecord::Base
  attr_accessible :content, :title, :location

  validates :content,     :presence => true
  validates :location,    :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index #The main site index in app/views/site
    @BlogPosts = BlogPost.order('id DESC').limit(5).page(params[:page]).per(5)
  end

  def page
    @page = SitePage.find(params[:id])
  end

  def post
    @blog_post = BlogPost.find(params[:id])

    offset = rand(BlogPost.count)
    @rand_record = BlogPost.order(:offset => offset).limit(3)

  end

  def category
    @category   = Category.find(params[:id])
    @blog_posts = BlogPost.where(:category_id => params[:id]).page(params[:page])
  end

  def search_results
    # Trying to implement category search
    @category = Category.where("title LIKE ?", "%#{params[:keywords]}%")

    if ( @category.first.nil? )
      @results = BlogPost.where("title LIKE ? OR content LIKE ?", 
                              "%#{params[:keywords]}%", "%#{params[:keywords]}%").page(params[:page])
    else
      @results = BlogPost.where("title LIKE ? OR content LIKE ? OR category_id LIKE ?", 
                                "%#{params[:keywords]}%", "%#{params[:keywords]}%", "%#{@category.first.id}%").page(params[:page])
    end
  end

  def blog
    @BlogPosts = BlogPost.order('id DESC').page(params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/blog_posts/_blog_post.html.erb
<div class="post">
	<h2><%= blog_post.title %></h2>
	<p>Posted In: <span class="post_category"><%= link_to blog_post.category.title , category_path(:id => blog_post.category.id) %></span></p>
	<p class="bp_created_at"><%= blog_post.created_at %></p>
	<% if blog_post.image_file_name %>
            <p class="featured_image_thumb"><%= image_tag blog_post.image.url(:thumb) %></p>
    <% end %>
    <p class="excerpt"><%= truncate(raw(strip_tags(blog_post.content)), :length => 240, :separator => ' ') %></p>
	<p class="read_more"><%= link_to "Read More", post_path(blog_post.id), :class => "product-btn btn btn-info" %></p>
</div><!--/span-->

app/views/footer/_footer.html.erb
<hr>

<% footer_widgets = Widget.where(:location => 'footer').limit(3) %>

  <footer>
    <p>&copy; Company 2013</p>
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCms</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% categories = Category.all %>
	<% pages      = SitePage.all %>
  <% widgets    = Widget.where('location' => 'sidebar') %>

<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "CMDann.ca", root_path, :class => "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Blog", blog_path %></li>
            <% pages.each do |page| %>
              <li><%= link_to page.title , page_path(:id => page.id) %></li>
            <% end %>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->

    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>

          <%= render 'search/search' %>

          <div class="row">
            
            <%= yield %>


          </div><!--/row-->
        </div><!--/span-->


        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
            <a href="#" class="list-group-item active">Categories:</a>
            <% categories.each do |category| %>
            	<%= link_to category.title , category_path(:id => category.id), :class=>"list-group-item" %>
          	<% end %>
          </div>

        <div class="col-lg-4">
        <% widgets.each do |widget| %>
          <div class="panel panel-primary side-bar-panel">
            <% if widget.title %>
              <div class="panel-heading">
                <h3 class="panel-title"><%= widget.title %></h3>
              </div>
            <% end %>
              <div class="panel-body">
                <%= raw(widget.content) %>
              </div>
            </div>
          
        <% end %>
        </div>
        </div><!--/span-->
      </div><!--/row-->

      <!-- Render the footer -->
      <%= render 'footer/footer' %>

    </div><!--/.container-->

</body>
</html>

app/views/search/_search.html.erb
<%= form_tag search_results_path :class => 'form-inline' do %>
        <%= text_field_tag :keywords, nil, placeholder: "Searh Site" , class: "form-control" %>
        <%= submit_tag 'Search', class: "btn btn-success" %>
<% end %>

app/views/site/blog.html.erb
<%= render @BlogPosts %>

<%= paginate @BlogPosts %>

app/views/site/category.html.erb
<h1><%= @category.title %></h1>
<p>Displaying <%= pluralize(@blog_posts.count, 'result') %></p>

<% if @blog_posts.empty? %>
    <div class="jumbotron">
       	<h1>No posts are in this category!</h1>
        <p>The category you searched for has no posts in it!</p>
        <p><%= link_to 'Take me home!', root_path, :class => "btn btn-lg btn-danger" %></p>
    </div>
<% end %>

<%= render @blog_posts %>

<%= paginate @blog_posts %>

app/views/site/index.html.erb
<div class="jumbotron">
<h1>CMDann.ca</h1>
<p>Tech, Programming, Computing.</p>
</div>

<%= render @BlogPosts %>
<%= paginate @BlogPosts %>

app/views/site/page.html.erb
<div class="jumbotron">
<h1><%= @page.title %></h1>
<p><%= raw(@page.content) %></p>
</div>

app/views/site/post.html.erb
<div class="jumbotron">
    <% if @blog_post.image_file_name %>
        <p class="featured_image"><%= image_tag @blog_post.image.url(:featured) %></p>
    <% end %>
	<h1><%= @blog_post.title %></h1>
	<p>Posted In: <span class="post_category"><%= link_to @blog_post.category.title , category_path(:id => @blog_post.category.id) %></span> On: <%= @blog_post.created_at %></p>
	<p><%= raw(@blog_post.content) %></p>
</div>

<!-- Random Posts -->
<h3>More from CMDann.ca</h2>
<% @rand_record.each do |random_post| %>
<div class="col-6 col-sm-6 col-lg-4">
	<h2><%= random_post.title %></h2>
	<p>Posted In: <span class="post_category"><%= random_post.category.title %></span> On: <%= random_post.updated_at %></p>
	<p></p>
	<p><%= link_to "Read More", post_path(random_post.id), :class => "product-btn btn btn-info" %></p>
</div><!--/span-->
<% end %>  

<!-- Comments -->
<h3>What do you think?</h2>
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'cmdannca'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/site/search_results.html.erb
<h2>Search Results</h2>
<p>Displaying <%= pluralize(@results.count, 'result') %></p>

<% if @results.empty? %>

        <div class="jumbotron">
        <h1>No Results Found!</h1>
        <p>Your search for '<%= params[:keywords] %>' has yielded you with not results my friend..</p>
        <p><%= link_to 'Take me home!', root_path, :class => "btn btn-lg btn-danger" %></p>
    </div>

<% end %>


<%= render @results %>

<%= paginate @results %>